export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Education & Experience",
  headLine: "1st Class BENG Computing Degree",
  description: "A Little About Me...",
  buttonLable: "See Work",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "skills",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Skills",
  headLine: "Languages & Tools",
  description: "Add boxes...",
  buttonLable: "See Work",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "skills",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "portfolio",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Portfolio",
  headLine: "Education & Personal Projects",
  description: "What I have done...",
  buttonLable: "See Work",
  imgStart: false,
  img: require("../../images/svg-3.svg").default,
  alt: "Portfolio",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFour = {
  id: "contact",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Contact",
  headLine: "Let's Work Together!",
  description: "Contact Me Now!",
  buttonLable: "Change this to a form",
  imgStart: true,
  img: require("../../images/svg-4.svg").default,
  alt: "skills",
  dark: false,
  primary: false,
  darkText: true,
};
